// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.debugger.settings;

import com.intellij.codeInsight.AnnotationsPanel;
import com.intellij.debugger.JavaDebuggerBundle;
import com.intellij.debugger.ui.JavaDebuggerSupport;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.options.Configurable.NoScroll;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.options.SearchableConfigurable;
import com.intellij.openapi.progress.ProcessCanceledException;
import com.intellij.openapi.project.IndexNotReadyException;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.Splitter;
import com.intellij.psi.PsiAnnotation;
import com.intellij.psi.PsiMethod;
import com.intellij.psi.PsiModifierListOwner;
import com.intellij.psi.PsiParameter;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ArrayUtilRt;
import com.intellij.util.containers.ContainerUtil;
import com.intellij.util.ui.JBUI;
import one.util.streamex.StreamEx;
import org.jetbrains.annotations.Async;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.ResourceBundle;

public final class CaptureConfigurable implements SearchableConfigurable, NoScroll {
  private static final Logger LOG = Logger.getInstance(CaptureConfigurable.class);
  private final Project myProject;

  private final JCheckBox myDebuggerAgent;
  private final JCheckBox myThrottling;
  private final JButton myConfigureAnnotationsButton;
  private final JPanel myPanel;

  public CaptureConfigurable(Project project) {
    myProject = project;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myPanel = new JPanel();
      myPanel.setLayout(new GridLayoutManager(3, 3, JBUI.emptyInsets(), -1, -1));
      myDebuggerAgent = new JBCheckBox();
      this.$$$loadButtonText$$$(myDebuggerAgent, this.$$$getMessageFromBundle$$$("messages/JavaDebuggerBundle",
                                                                                 "label.capture.configurable.debugger.agent"));
      myPanel.add(myDebuggerAgent, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                                                       GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null,
                                                       0, false));
      final Spacer spacer1 = new Spacer();
      myPanel.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                               GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myConfigureAnnotationsButton = new JButton();
      this.$$$loadButtonText$$$(myConfigureAnnotationsButton, this.$$$getMessageFromBundle$$$("messages/JavaDebuggerBundle",
                                                                                              "label.capture.configurable.annotations.configure"));
      myPanel.add(myConfigureAnnotationsButton,
                  new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                      GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myThrottling = new JBCheckBox();
      this.$$$loadButtonText$$$(myThrottling,
                                this.$$$getMessageFromBundle$$$("messages/JavaDebuggerBundle", "label.capture.configurable.throttling"));
      myPanel.add(myThrottling,
                  new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
      final Spacer spacer2 = new Spacer();
      myPanel.add(spacer2,
                  new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                      GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myPanel; }

  @Override
  public @NotNull String getId() {
    return getHelpTopic();
  }

  @Override
  public @NotNull String getHelpTopic() {
    return "reference.idesettings.debugger.capture";
  }

  @Override
  public @Nullable JComponent createComponent() {
    myConfigureAnnotationsButton.addActionListener(e -> new AsyncAnnotationsDialog(myProject).show());

    myDebuggerAgent.addChangeListener(e -> setThrottlingCheckboxEnabled());
    setThrottlingCheckboxEnabled();
    return myPanel;
  }

  private void setThrottlingCheckboxEnabled() {
    myThrottling.setEnabled(myDebuggerAgent.isSelected());
  }

  @Override
  public boolean isModified() {
    return DebuggerSettings.getInstance().INSTRUMENTING_AGENT != myDebuggerAgent.isSelected() ||
           DebuggerSettings.getInstance().AGENT_THROTTLING != myThrottling.isSelected();
  }

  @Override
  public void apply() throws ConfigurationException {
    DebuggerSettings.getInstance().INSTRUMENTING_AGENT = myDebuggerAgent.isSelected();
    DebuggerSettings.getInstance().AGENT_THROTTLING = myThrottling.isSelected();
  }

  @Override
  public void reset() {
    myDebuggerAgent.setSelected(DebuggerSettings.getInstance().INSTRUMENTING_AGENT);
    myThrottling.setSelected(DebuggerSettings.getInstance().AGENT_THROTTLING);
  }

  @Override
  public @Nls String getDisplayName() {
    return JavaDebuggerBundle.message("async.stacktraces.configurable.display.name");
  }

  interface CapturePointConsumer<R> {
    R accept(boolean capture, PsiModifierListOwner e, PsiAnnotation annotation);
  }

  static <R> List<R> processCaptureAnnotations(@Nullable Project project, CapturePointConsumer<R> consumer) {
    if (project == null) { // fallback
      project = JavaDebuggerSupport.getContextProjectForEditorFieldsInDebuggerConfigurables();
    }
    if (project.isDefault()) {
      return Collections.emptyList();
    }
    DebuggerProjectSettings debuggerProjectSettings = DebuggerProjectSettings.getInstance(project);
    return ContainerUtil.concat(
      scanPointsInt(project, debuggerProjectSettings, true, consumer),
      scanPointsInt(project, debuggerProjectSettings, false, consumer));
  }

  private static <R> List<R> scanPointsInt(Project project,
                                           DebuggerProjectSettings debuggerProjectSettings,
                                           boolean capture,
                                           CapturePointConsumer<R> consumer) {
    try {
      return NodeRendererSettings.visitAnnotatedElements(getAsyncAnnotations(debuggerProjectSettings, capture), project,
                                                         (e, annotation) -> consumer.accept(capture, e, annotation),
                                                         PsiMethod.class, PsiParameter.class);
    }
    catch (IndexNotReadyException | ProcessCanceledException ignore) {
    }
    catch (Exception e) {
      LOG.error(e);
    }
    return Collections.emptyList();
  }

  static String getAnnotationName(boolean capture) {
    return (capture ? Async.Schedule.class : Async.Execute.class).getName().replace("$", ".");
  }

  private static List<String> getAsyncAnnotations(DebuggerProjectSettings debuggerProjectSettings, boolean capture) {
    return StreamEx.of(capture ? debuggerProjectSettings.myAsyncScheduleAnnotations : debuggerProjectSettings.myAsyncExecuteAnnotations)
      .prepend(getAnnotationName(capture))
      .toList();
  }

  private final class AsyncAnnotationsDialog extends DialogWrapper {
    private final AnnotationsPanel myAsyncSchedulePanel;
    private final AnnotationsPanel myAsyncExecutePanel;
    private final DebuggerProjectSettings mySettings;

    private AsyncAnnotationsDialog(@NotNull Project project) {
      super(project, true);
      mySettings = DebuggerProjectSettings.getInstance(myProject);
      myAsyncSchedulePanel = new AnnotationsPanel(project,
                                                  JavaDebuggerBundle.message("settings.async.schedule"),
                                                  getAsyncAnnotations(mySettings, true),
                                                  Collections.singletonList(getAnnotationName(true))
      );
      myAsyncExecutePanel = new AnnotationsPanel(project,
                                                 JavaDebuggerBundle.message("settings.async.execute"),
                                                 getAsyncAnnotations(mySettings, false),
                                                 Collections.singletonList(getAnnotationName(false))
      );
      init();
      setTitle(JavaDebuggerBundle.message("settings.async.annotations.configuration"));
    }

    @Override
    protected JComponent createCenterPanel() {
      final Splitter splitter = new Splitter(true);
      splitter.setFirstComponent(myAsyncSchedulePanel.getComponent());
      splitter.setSecondComponent(myAsyncExecutePanel.getComponent());
      splitter.setHonorComponentsMinimumSize(true);
      splitter.setPreferredSize(JBUI.size(300, 400));
      return splitter;
    }

    @Override
    protected void doOKAction() {
      mySettings.myAsyncScheduleAnnotations = StreamEx.of(myAsyncSchedulePanel.getAnnotations())
        .filter(e -> !e.equals(getAnnotationName(true)))
        .toArray(ArrayUtilRt.EMPTY_STRING_ARRAY);
      mySettings.myAsyncExecuteAnnotations = StreamEx.of(myAsyncExecutePanel.getAnnotations())
        .filter(e -> !e.equals(getAnnotationName(false)))
        .toArray(ArrayUtilRt.EMPTY_STRING_ARRAY);
      super.doOKAction();
    }

    @Override
    protected @NotNull String getHelpId() {
      return "reference.idesettings.debugger.customAsyncAnnotations";
    }
  }
}
