// Copyright 2000-2026 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.k2.copyPaste;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.base.test.TestRoot;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("code-insight/kotlin.code-insight.k2")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("testData/copyPaste/plainTextImports")
public class K2PlainTextImportsCopyPastePostProcessorTestGenerated extends AbstractK2PlainTextImportsCopyPastePostProcessorTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    @TestMetadata("DuplicateImport.test")
    public void testDuplicateImport() throws Exception {
        runTest("testData/copyPaste/plainTextImports/DuplicateImport.test");
    }

    @TestMetadata("ImportInKotlinFile.test")
    public void testImportInKotlinFile() throws Exception {
        runTest("testData/copyPaste/plainTextImports/ImportInKotlinFile.test");
    }

    @TestMetadata("ImportInScript.test")
    public void testImportInScript() throws Exception {
        runTest("testData/copyPaste/plainTextImports/ImportInScript.test");
    }

    @TestMetadata("NonLeadingImport.test")
    public void testNonLeadingImport() throws Exception {
        runTest("testData/copyPaste/plainTextImports/NonLeadingImport.test");
    }
}
